export const StudentConstants = {
    GET_STUDENT_LIST_REQUEST: 'GET_STUDENT_LIST_REQUEST',
    GET_STUDENT_LIST_SUCCESS: 'GET_STUDENT_LIST_SUCCESS',
    GET_STUDENT_LIST_AILURE: 'GET_STUDENT_LIST_FAILURE',
  };
